# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Treasure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name=b'Name')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name=b'Value')),
                ('material', models.CharField(max_length=100, verbose_name=b'Material')),
                ('location', models.CharField(max_length=100, verbose_name=b'Location')),
                ('img_url', models.CharField(max_length=10000, verbose_name=b'Img_url')),
            ],
        ),
    ]
