# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170720_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.ImageField(upload_to=b'treasure_image/'),
        ),
    ]
