# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20170720_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treasure',
            name='image',
            field=models.CharField(max_length=1000, verbose_name=b'Image'),
        ),
    ]
